package org.nightlabs.jfire.base.ui.person.create;

import java.lang.reflect.InvocationTargetException;

import org.eclipse.core.runtime.IProgressMonitor;
import org.eclipse.jface.operation.IRunnableWithProgress;
import org.eclipse.jface.viewers.IStructuredSelection;
import org.eclipse.ui.INewWizard;
import org.eclipse.ui.IWorkbench;
import org.nightlabs.base.ui.progress.ProgressMonitorWrapper;
import org.nightlabs.base.ui.wizard.DynamicPathWizard;
import org.nightlabs.jfire.base.ui.person.search.PersonEditorWizardHop;
import org.nightlabs.jfire.idgenerator.IDGenerator;
import org.nightlabs.jfire.person.Person;
import org.nightlabs.jfire.prop.PropertySet;
import org.nightlabs.jfire.prop.StructLocal;
import org.nightlabs.jfire.prop.dao.PropertySetDAO;
import org.nightlabs.jfire.prop.dao.StructLocalDAO;
import org.nightlabs.jfire.security.SecurityReflector;
import org.nightlabs.progress.NullProgressMonitor;
import org.nightlabs.progress.ProgressMonitor;
import org.nightlabs.progress.SubProgressMonitor;

/**
 * @author Chairat Kongarayawetchakun - chairat[at]nightlabs[dot]de
 */
public class CreatePersonWizard
extends DynamicPathWizard
implements INewWizard
{
	private Person newPerson;
	private PersonEditorWizardHop newPersonEditorWizardHop;

	public CreatePersonWizard()
	{
		setWindowTitle("");
	}

	/**
	 * Adding the page to the wizard.
	 */
	@Override
	public void addPages() {
		newPerson = new Person(
				SecurityReflector.getUserDescriptor().getOrganisationID(),
				IDGenerator.nextID(PropertySet.class)
		);
		StructLocal structLocal = StructLocalDAO.sharedInstance().getStructLocal(
				newPerson.getStructLocalObjectID(),
				new NullProgressMonitor()
		);
		newPerson.inflate(structLocal);
		newPerson.setAutoGenerateDisplayName(true);

		newPersonEditorWizardHop = new PersonEditorWizardHop();
		newPersonEditorWizardHop.initialise(newPerson);

		newPersonEditorWizardHop.getEntryPage().setTitle("Create new person");
		addPage(newPersonEditorWizardHop.getEntryPage());
	}

	@Override
	public boolean performFinish() {
		try {
			getContainer().run(false, false, new IRunnableWithProgress() {
				public void run(IProgressMonitor _monitor) throws InvocationTargetException, InterruptedException {
					ProgressMonitor monitor = new ProgressMonitorWrapper(_monitor);
					monitor.beginTask("Begin...", 100);
					try {
						newPerson.deflate();
						newPerson = (Person) PropertySetDAO.sharedInstance().storeJDOObject(
								newPerson, true, null, 1,
								new SubProgressMonitor(monitor, 2)
						);
					} finally {
						monitor.done();
					}
				}
			});
		} catch (Exception e) {
			throw new RuntimeException(e);
		}
		return true;
	}


	/* (non-Javadoc)
	 * @see org.eclipse.ui.IWorkbenchWizard#init(org.eclipse.ui.IWorkbench, org.eclipse.jface.viewers.IStructuredSelection)
	 */
	@Override
	public void init(IWorkbench workbench, IStructuredSelection selection) {
		// do nothing
	}

	public Person getPerson() {
		return newPerson;
	}
}